apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
  labels:
    type: local-mysql
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.mysql.resources.limits.memory }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-volume-claim
  labels:
    type: local-mysql
    db: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.resources.requests.memory }}

